### ISSUE TITLE
Replay TV

### ISSUE THREAD

**Issue by kedarz** [kpl-addons/plugin.video.upc2#1]
Dzieki za super wtyczke. 
Czy we wtyczce jest mozliwosc ogladania Replay TV, bo w ustawieniach widze odswiezanie tokena ale nigdzie nie widze mozliwosci odtwarzania zaleglych programow ?

**Comment by hevet** [comment]
Tak, powinno być w Telewizja - Replay TV.

**Comment by Cinek77** [comment]
Jeśli jest w pakiecie Replay TV. Jak nie ma to nie wyświetli.
https://prnt.sc/EaWO6MGSjlz8

**Comment by kedarz** [comment]
Kanaly na zywo wg kategorii jak sama nazwa mowi to tylko rodzaj sortowania. We wtyczce Horizon Go od mbebe mozna bylo ogladac do siedmu dni wstecz. 

> Jeśli jest w pakiecie Replay TV. Jak nie ma to nie wyświetli. https://prnt.sc/EaWO6MGSjlz8

**Comment by kedarz** [comment]
> Tak, powinno być w Telewizja - Replay TV.

Niestety nie mam a w Horizon Go mialem. Tu po wejsciu w kanaly tv na zywo wyswietla mi sie id razu lista kanalow.

**Comment by mtr81** [comment]
W nowym API obecność usługi replay TV jest weryfikowana w inny sposób niż w starym (kiedyś wprost przez odpowiednią wartość parametru 'isReplay'). W Ustawieniach wtyczki- w jednej z zakładek - masz symbole usług posiadanych w pakiecie. W chwili obecnej sekcja Replay TV jest pokazywana we wtyczce dla symboli "replaytv" oraz "TVOD". Podaj mi skróty ze swojej tablicy. Być może usługa replay w Twoim pakiecie jest inaczej opisana. Jeśli tak zaktualizuję wtyczkę, aby sekcja ReplayTV się wyświetlała.

**Comment by kedarz** [comment]
W zakladce "Informacje dodatkowe" Uslugi w pakiecie mam czyste pole.

**Comment by hevet** [comment]
U mnie jest TV180 i replaytv.

**Comment by mtr81** [comment]
@kedarz spróbuj się wylogować i zalogować ponownie. To pole nie powinno być puste. W ekstremalnej sytuacji powinieneś zobaczyć przynajmniej kwadratowe nawiasy...

**Comment by kedarz** [comment]
Pomoglo. Dziekuje
