### ISSUE TITLE
UPC M3U Grupy i Catchup

### ISSUE THREAD

**Issue by zaqwa321** [kpl-addons/plugin.video.upc2#2]
Czy byłaby możliwość generowania m3u z przydzielonymi grupami TV np. group-title="Ogólne" ,... 
oraz parametrami catchup lub catchup="default". 
Jakie są parametry catchup ?
Dla popularnego dostawcy tele będzie to: ?utc={utc}&lutc={lutc} Dla popularnego dostawcy +X będzie to: &utc={utc}&lutc={lutc} 
dla UPC ani jedno ani drugie nie działa z wtyczką PVR IPTV Simple jak opisano w artykule 
https://kodiwpigulce.pl/jak-skonfigurowac-pvr-iptv-simple-client-z-wlasna-lista-i-archiwum-w-kodi-19-poradnik/

**Comment by mtr81** [comment]
Już ci pisałem w innym miejscu. Catchup w upc jest nieosiągalny. Korzystaj z zakładki ReplayTV we wtyczce.

**Comment by zaqwa321** [comment]
> Już ci pisałem w innym miejscu. Catchup w upc jest nieosiągalny. Korzystaj z zakładki ReplayTV we wtyczce.

Dzięki za informację nt Catchup. 
A co eksportem grup kanałów? Skoro wtyczka "czyta" to chyba można zapisać.

**Comment by mtr81** [comment]
Nad grupami w liście się pochylę. Z ich wrzuceniem to nie będzie problemu, tylko muszę rozważyć czy to ma sens, bo i tak to ostatecznie użytkownik scalając listy z różnych wtyczek i serwisów decyduje o grupowaniu kanałów...
