### ISSUE TITLE
Invalid Token

### ISSUE THREAD

**Issue by zaqwa321** [kpl-addons/plugin.video.upc2#3]
Mam komunika Invalid token nie udaje mi się otworzyć programów UPC. Co się da z tym zrobić?

**Comment by mtr81** [comment]
Wyloguj się i zaloguj ponownie. W repo KWP jest nieaktualna wersja wtyczki. Na dniach wrzucę poprawkę, która wyeliminuje problem (nie będzie potrzebne przelogowanie)
EDIT:
aktualna wersja już wysłana
